//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_Order { get; set; }
        public string OrderList { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> IDPointOfIssue { get; set; }
        public string FIO { get; set; }
        public string Code { get; set; }
        public string Status { get; set; }
    
        public virtual PointOfIssue PointOfIssue { get; set; }
    }
}
